### PR TITLE
Update .gitignore

### PR DESCRIPTION
**Pull request by xbony2**

### CODE REVIEW

**Comment by retep998** [comment]
Friggin macs.

**Comment by elifoster** [comment]
@xbony2 Just add it to your damn global gitignore like everyone else. Adding OS specific things to repo gitignores is messy.

**Comment by xbony2** [comment]
It's only messy if you have actual-used-files-in-my-gitignore-phobia.

**Comment by elifoster** [comment]
It's messy because repository gitignores should only contain files relevant to the project; not the people developing it.

**Pull request merged**
